name: transiteta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - shapely=2.0.6
  - ipykernel=6.29.5
  - nb_conda_kernels=2.5.1
  - jupyter=1.1.1
  - psycopg2=2.9.9
  - requests=2.32.3
  - pip=24.0
  - pip:
    - gtfs-realtime-bindings==1.0.0
